
/**
* User Actions
**/

export const USER_START_LOGIN                   = 'USER_START_LOGIN'
export const USER_SUCCESSFULLY_LOGGED           = 'USER_SUCCESSFULLY_LOGGED'
export const USER_LOGIN_FAILED                  = 'USER_LOGIN_FAILED'
export const USER_START_REGISTER                = 'USER_START_REGISTER'
export const USER_REGISTERED_SUCCESSFULLY       = 'USER_REGISTERED_SUCCESSFULLY'
export const USER_REGISTER_FAILED               = 'USER_REGISTER_FAILED'
export const USER_LOGGED_OUT                    = 'USER_LOGGED_OUT'
export const USER_START_RESET_PASSWORD          = 'USER_START_RESET_PASSWORD'
export const USER_PASSWORD_SUCCESSFULLY_RESET   = 'USER_PASSWORD_SUCCESSFULLY_RESET'
export const USER_PASSWORD_RESET_FAILED         = 'USER_PASSWORD_RESET_FAILED'
export const USER_START_CHANGE_PASSWORD         = 'USER_START_CHANGE_PASSWORD'
export const USER_PASSWORD_SUCCESSFULLY_CHANGED = 'USER_PASSWORD_SUCCESSFULLY_CHANGED'
export const USER_PASSWORD_CHANGE_FAILED        = 'USER_PASSWORD_CHANGE_FAILED'

/**
* Products Actions
**/

export const START_PRODUCTS_RETRIEVE            = 'START_PRODUCTS_RETRIEVE'
export const PRODUCTS_RETRIEVED_SUCCESSFULLY    = 'PRODUCTS_RETRIEVED_SUCCESSFULLY'
export const PRODUCTS_RETRIEVE_FAILED           = 'PRODUCTS_RETRIEVE_FAILED'
export const START_PRODUCT_INSERT               = 'START_PRODUCT_INSERT'
export const PRODUCT_INSERTED_SUCCESSFULLY      = 'PRODUCT_INSERTED_SUCCESSFULLY'
export const PRODUCT_INSERT_FAILED              = 'PRODUCT_INSERT_FAILED'
export const LOAD_PRODUCT                       = 'LOAD_PRODUCT'
export const START_PRODUCT_UPDATE               = 'START_PRODUCT_UPDATE'
export const PRODUCT_UPDATED_SUCCESSFULLY       = 'PRODUCT_UPDATED_SUCCESSFULLY'
export const PRODUCT_UPDATE_FAILED              = 'PRODUCT_UPDATE_FAILED'
