
/**
* User Actions
**/

export const USER_START_LOGIN                   = 'USER_START_LOGIN'
export const USER_SUCCESSFULLY_LOGGED           = 'USER_SUCCESSFULLY_LOGGED'
export const USER_LOGIN_FAILED                  = 'USER_LOGIN_FAILED'
export const USER_START_REGISTER                = 'USER_START_REGISTER'
export const USER_REGISTERED_SUCCESSFULLY       = 'USER_REGISTERED_SUCCESSFULLY'
export const USER_REGISTER_FAILED               = 'USER_REGISTER_FAILED'
export const USER_LOGGED_OUT                    = 'USER_LOGGED_OUT'
export const USER_START_RESET_PASSWORD          = 'USER_START_RESET_PASSWORD'
export const USER_PASSWORD_SUCCESSFULLY_RESET   = 'USER_PASSWORD_SUCCESSFULLY_RESET'
export const USER_PASSWORD_RESET_FAILED         = 'USER_PASSWORD_RESET_FAILED'
export const USER_START_CHANGE_PASSWORD         = 'USER_START_CHANGE_PASSWORD'
export const USER_PASSWORD_SUCCESSFULLY_CHANGED = 'USER_PASSWORD_SUCCESSFULLY_CHANGED'
export const USER_PASSWORD_CHANGE_FAILED        = 'USER_PASSWORD_CHANGE_FAILED'
export const USER_START_CHANGE_DATA             = 'USER_START_CHANGE_DATA'
export const USER_DATA_SUCCESSFULLY_CHANGED     = 'USER_DATA_SUCCESSFULLY_CHANGED'
export const USER_DATA_CHANGE_FAILED            = 'USER_DATA_CHANGE_FAILED'

/**
* Products Actions
**/

export const START_PRODUCTS_RETRIEVE            = 'START_PRODUCTS_RETRIEVE'
export const PRODUCTS_RETRIEVED_SUCCESSFULLY    = 'PRODUCTS_RETRIEVED_SUCCESSFULLY'
export const PRODUCTS_RETRIEVE_FAILED           = 'PRODUCTS_RETRIEVE_FAILED'
export const START_PRODUCT_INSERT               = 'START_PRODUCT_INSERT'
export const PRODUCT_INSERTED_SUCCESSFULLY      = 'PRODUCT_INSERTED_SUCCESSFULLY'
export const PRODUCT_INSERT_FAILED              = 'PRODUCT_INSERT_FAILED'
export const LOAD_PRODUCT                       = 'LOAD_PRODUCT'
export const START_PRODUCT_UPDATE               = 'START_PRODUCT_UPDATE'
export const PRODUCT_UPDATED_SUCCESSFULLY       = 'PRODUCT_UPDATED_SUCCESSFULLY'
export const PRODUCT_UPDATE_FAILED              = 'PRODUCT_UPDATE_FAILED'

/**
* Categories Actions
**/

export const START_CATEGORIES_RETRIEVE          = 'START_CATEGORIES_RETRIEVE'
export const CATEGORIES_RETRIEVED_SUCCESSFULLY  = 'CATEGORIES_RETRIEVED_SUCCESSFULLY'
export const CATEGORIES_RETRIEVE_FAILED         = 'CATEGORIES_RETRIEVE_FAILED'
export const START_CATEGORY_INSERT              = 'START_CATEGORY_INSERT'
export const CATEGORY_INSERTED_SUCCESSFULLY     = 'CATEGORY_INSERTED_SUCCESSFULLY'
export const CATEGORY_INSERT_FAILED             = 'CATEGORY_INSERT_FAILED'
export const START_CATEGORY_REMOVE              = 'START_CATEGORY_REMOVE'
export const CATEGORY_REMOVED_SUCCESSFULLY      = 'CATEGORY_REMOVED_SUCCESSFULLY'
export const CATEGORY_REMOVE_FAILED             = 'CATEGORY_REMOVE_FAILED'

/**
* Address Actions
**/

export const START_ADDRESS_INSERT               = 'START_ADDRESS_INSERT'
export const ADDRESS_INSERTED_SUCCESSFULLY      = 'ADDRESS_INSERTED_SUCCESSFULLY'
export const ADDRESS_INSERT_FAILED              = 'ADDRESS_INSERT_FAILED'
